namespace: northstar
api:
  image: ghcr.io/akash-verma-11/northstar-api
  tag: "4f9c3820be5dd0774e3bbab244741fdac18d8584"
  pullPolicy: IfNotPresent
  replicas: 2
frontend:
  image: ghcr.io/akash-verma-11/northstar-frontend
  tag: "4f9c3820be5dd0774e3bbab244741fdac18d8584"
  pullPolicy: IfNotPresent
  replicas: 2
worker:
  image: ghcr.io/akash-verma-11/northstar-worker
  tag: "4f9c3820be5dd0774e3bbab244741fdac18d8584"
  pullPolicy: IfNotPresent
  replicas: 2
postgres:
  image: postgres
  tag: "17-alpine"
  user: app
  dbName: orders
  storageSize: 1Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
ingress:
  host: orders.local
  className: nginx
  local: true
