FROM jenkins/inbound-agent:latest-jdk21
USER root
RUN apt-get update && apt-get install -y \
    docker.io python3 python3-pip python3-venv git curl \
    && rm -rf /var/lib/apt/lists/*
RUN groupmod -g 986 docker
RUN usermod -aG docker jenkins
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
RUN curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq
USER jenkins
