sonar.projectKey=northstar-order-platform
sonar.projectName=Northstar Order Platform
sonar.organization=akash-verma-11

# Define your source directories
sonar.sources=backend,worker,frontend/src

# Explicitly exclude the tests folder from the source analysis
sonar.exclusions=backend/tests/**

# Define where your test files are located
sonar.tests=backend/tests