sonar.projectKey=Akash-Verma-11_northstar-order-platform
sonar.organization=akash-verma-11
sonar.projectName=Northstar Order Platform
sonar.sources=backend,worker,frontend/src
sonar.tests=backend/tests