apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: northstar-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Akash-Verma-11/northstar-order-platform.git
    targetRevision: main
    path: helm/northstar
    helm:
      valueFiles: [values.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: northstar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
